
# CodeDeploy 버전
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

# CodeDeploy 에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다.
permission:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# CodeDeploy 배포 단계에서 실행할 명령어를 지정
hooks:
  ApplicationStart:     # ApplicationStart 단계에서 deploy.sh 를 ec2-user 권한으로 실행
    - location: deploy.sh
      timeout: 60       # 스크립트 실행이 60초 이상 수행되면 실패 처리
      runas: ec2-user


