spring:
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
      
  profiles:
    include: oauth

  session:
    store-type: jdbc

server:
  port: 8080
